matrix:
  include:
    - env: PLATFORM='linux64'
      os: linux
      dist: xenial
      sudo: required
      compiler: clang
      language: cpp
      cache:
        ccache: true
        directories:
          - $HOME/.ccache
          - $HOME/.cache/apt

script:
  - bash scripts/ci-${PLATFORM}.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

