language: cpp
compiler: gcc
sudo: require
dist: xenial
cache:
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/.cache/apt
  - $HOME/.cache/mpv-build

before_install:
  - mkdir -p $HOME/.cache/apt/partial
  - sudo rm -rf /var/cache/apt/archives
  - sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
  - sudo apt-get update 

install:
  - sudo apt-get -y install nasm ccache qt511-meta-minimal qt511quickcontrols qt511quickcontrols2 qt511imageformats qt511svg libgl1-mesa-dev 
  - sudo apt-get build-dep libmpv1
  - source /opt/qt*/bin/qt*-env.sh

script:
  - bash scripts/makeappimage.sh

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file KittehPlayer*.AppImage https://transfer.sh/KittehPlayer-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh KittehPlayer*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

