language: cpp
compiler: gcc
sudo: require
dist: xenial
cache:
  paths:
  - $TRAVIS_BUILD_DIR/apt-cache/

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/apt-cache/
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
  - sudo apt-get update 

install:
  - sudo apt-get -o dir::cache::archives="$TRAVIS_BUILD_DIR/apt-cache" -y install libmpv-dev qt511-meta-minimal qt511quickcontrols qt511quickcontrols2  qt511imageformats qt511svg libavcodec-dev libavcodec-extra libgl1-mesa-dev 
  - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
  - chmod a+x linuxdeploy-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - mkdir -p appdir/usr/plugins/imageformats/
  - cp /opt/qt*/plugins/imageformats/libqsvg.so appdir/usr/plugins/imageformats/
  - #./linuxdeploy-x86_64.AppImage appdir/usr/share/applications/*.desktop -qmldir=./src/qml/ -bundle-non-qt-libs
  - ./linuxdeploy-x86_64.AppImage --appdir AppDir -e KittehPlayer -i KittehPlayer.png -d KittehPlayer.desktop --plugin qt --output appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file KittehPlayer*.AppImage https://transfer.sh/KittehPlayer-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - #bash upload.sh KittehPlayer*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
